### ISSUE TITLE
Qlik Sense BigQuery Connection string parameters

### ISSUE THREAD

**Issue by itsakshaye** [ahaydon/Qlik-Cli-Windows#111]
Where i can find connection string parameters for Google BigQuery ODBC connector within Qlik Sense for creating connection using PowerShell.

**Comment by Nillth** [comment]
The data connection string is a string value you need to supply. there is no constructor for it in the module.

e.g. a you would submit the following as the BigData Connection String:

`CUSTOM CONNECT TO "provider=QvOdbcConnectorPackage.exe;driver=gbq;ClientId=<Key Omitted>;ClientSecret=<Secret Omitted>;RefreshToken=<Refrest Omitted>;OAuthMechanism=1;Catalog=nnet-237909;SQLDialect=1;EnableSQLPrepareMetadataWithLegacySQL=false;UseLegacySQLMetadata=0;AllowLargeResultSets=false;AllowLargeResults=0;LargeResultDataSetId=_odbc_temp_tables;LargeResultsTempTableExpirationTime=3600000;RowsFetchedPerBlock=16384;DefaultStringColumnLength=65535;UseSystemTrustStore=1;QueryTimeout=30;"`

**Comment by itsakshaye** [comment]
Hey, We need this for Service Authentication. I try same way but for Service Key file its not working. Not sure how & in which format we need to store this details in QS db prior to creating connection.

**Comment by ahaydon** [comment]
I suggest creating the connection manually first as it's much easier with the GUI, then once you have it working you can copy the connection string from QMC to use for automation.

**Comment by itsakshaye** [comment]
Hi ahaydon,

We are able to create Cnnection string using GUI. However in BigQuery connector once you supply Email & Service Key file details & Click Validate those details get store in QS Postgres DB. We are not sure how to implement this part where we need to store details in QS Postgres DB. We have been stuck at this part for our automation.

Let me know if we can do this.

Thanks,
Akshaye

**Comment by Nillth** [comment]
Stale
