### ISSUE TITLE
Issue conneting to Qlik Sense via Qlik CLI

### ISSUE THREAD

**Issue by minpsd** [ahaydon/Qlik-Cli-Windows#123]
Hello - I'm having an issue where I cannot connect the Qlik Sense using certificates. I was able to install Qlik CLI and was able to run 'Get-Help Qlik' to verify the it's installed. However, I tried to use this command below to connect to Qlik Sense (changed some parameters to keep things private) which would run with no errors:

Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'hostname'} | Connect-Qlik hostname -username domain\username

However, thenI tried to run other Qlik Cli command to test it out since I have to export/import Qlik Sense app from Dev to Staging i.e Get-QlikApp -filter "name eq 'Test App'" -full or (Get-QlikApp -full).count
I would get this error:
Invoke-RestMethod : Unable to connect to the remote server
or
Invoke-RestMethod : The remote server returned an error: (401) Unauthorized

So I'm not sure how to fix this issue cause if I can't successfully connect to Qlik Sense then I can't do anything else. Let me know if you need more information
Please help, thank you!

**Comment by ahaydon** [comment]
A 401 error suggests that it was unable to authenticate with certificates and fell back to Windows auth, you can check this by adding the -Verbose flag to the Connect-Qlik command.
I suggest running `Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'hostname'}` and checking that it outputs the correct certificate and that there is only one result.

**Comment by minpsd** [comment]
I see. I tried to include -Verbose into the Connect-Qlik command by running this `Connect-Qlik -verbose` command and it seems like I'm connected to the Qlik client certificate that I imported to my machine. The output also had 'VERBOSE: GET https://xxxx with 0-byte payload' then the next output after that line was this error :
Invoke-RestMethod : Unable to connect to the remote server

When I tried to run test command, it gave me this error again:
Invoke-RestMethod : Unable to connect to the remote server

However when I tried to run `Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'hostname'}` - there was no output so I'm not sure if I'm doing something wrong or does it mean that it's connecting to the certificate and that's why there's no output?

Thank you again for your help!

**Comment by ahaydon** [comment]
You need to use wildcards with the -like comparator, so should be '*hostname*' or 'cn=hostname-ca'. If the certificate is there the Connect-Qlik command should find it automatically so you shouldn't need to even use Get-ChildItem unless you have multiple certificates that match.

If the verbose output says that it connected with certificate QlikClient then it may be that the certificate is not trusted or some other connectivity issue. It should also tell you the username it is authenticating as, which should be the account you are running PS as.

**Comment by minpsd** [comment]
Okay when I ran `Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'cn=hostname-ca' }` - the output list the QlikClient cert (output: CN=QlikClient) and there's only one there

But when I tried to connect to Qlik Sense and run `Connect-Qlik -computername hostname -username domain\username` (that I got from -Verbose) by itself, now it prompted me to input the certificate even though I already checked that it's there:
_cmdlet Connect-Qlik at command pipeline position 1
Supply values for the following parameters:
Certificate:_

So I'm still pretty stuck, unfortunately. I really appreciate all your help!

**Comment by ahaydon** [comment]
When you specify a username you need to also provide a certificate, which you can do with pipelining as you were doing originally.
`Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'cn=hostname-ca'} | Connect-Qlik hostname -username domain\username`

If you are running the commands on the Sense server you should just be able to run `Connect-Qlik` without any parameters.

To connect remotely as the logged on user, and assuming you have a certificate installed locally, you can use `Connect-Qlik -computername hostname`

**Comment by minpsd** [comment]
Oh I see. I tried to run this command `Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'cn=hostname-ca'} | Connect-Qlik hostname -username domain\username` like you mentioned above but I got this errors. I'm running Powershell as an admin if that helps:

Get-ChildItem : Unable to connect to the remote server
At line:1 char:1
+ Get-ChildItem -Path cert:\CurrentUser\My | where {$_.issuer -like 'cn ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Get-ChildItem], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.GetChildItemCommand

So I'm not sure what else I need to do...again I really appreciate your help!

**Comment by ahaydon** [comment]
When connecting with certificates it will connect to the machine on port 4242, you can check if that port is accessible using `Test-NetConnection -ComputerName hostname -Port 4242`, if successful it should show `TcpTestSucceeded: True`

If you're not running the commands on the Sense server then you may not have trusted the Sense CA, you can either import the root certificate from Sense into your local certificate store or use the insecure option `-TrustAllCerts` on the Connect-Qlik command.

**Comment by minpsd** [comment]
I see. I was able to run Qlik-Cli commands (i.e. Get-QlikApp) on Qlik server so thank you for you your help! I've been trying to connect to Qlik from Qlik-Cli for the past two days and you helped so much!

However, now I have a question about `Export-QlikApp` command. I tried to export a test app from Qlik with this command using app id `Export-QlikApp -id xxxxxxxxx` but it didn't work and gave me this error:

Invoke-RestMethod: The remote server returned an error: (403) Forbidden

Do you know how to fix this issue? Other commands like `Get-QlikApp` works but I'm also having troubles with specifying parameters as well like in `Export-QlikApp`. I'm new to Powershell so thank you again for all your help!

**Comment by Nillth** [comment]
#Set the following variables
```
$QlikUser = "userdirectory\userid"
$ExportPath = "C:\Temp"
```

#Gets all certificates that have the name CN=QlikClient (the certificate you should be using)
`$Certs = Get-ChildItem -Recurse Cert:\CurrentUser\My\|?{$_.Subject -eq "CN=QlikClient"}`

#connects using the First Certificate (if more than one: increment $Certs[0] to try another)
`Connect-Qlik -Computername "$($env:COMPUTERNAME)" -TrustAllCerts -Certificate $Certs[0] -Username $QlikUser `

#Get the Qlik apps
`$apps = Get-QlikApp `

# Select a app from the out grid
`$selectedApps = $apps|Out-GridView -PassThru`

#Export the selected apps
```
foreach ($selectedApp in $selectedApps){
    Export-QlikApp -id $selectedApp.id -filename $(Join-Path -Path $ExportPath -ChildPath "$($selectedApp.id).qvf")
}
```

Alternatively 
#Specify the ID of the App to Export & where you want to export it
`Export-QlikApp -id "6055af35-e442-466b-94b6-076fdda233ce" -filename "C:\Export\Myapp.qvf"`

**Comment by minpsd** [comment]
Thanks for your answer! I was able to connect and ran export/import Qlik Cli on Qlik server

**Comment by xDloogix** [comment]
@minpsd can you please let me now what helped in your case? I have a similar issue and been trying to connect to QLIK server and keep on getting the same result as you.
