### ISSUE TITLE
Missing commands? Get-QlikAbout

### ISSUE THREAD

**Issue by ryanplkam** [ahaydon/Qlik-Cli-Windows#124]
When I attempt to connect using Connect-Qlik, I get the following error message:

Get-QlikAbout : The term 'Get-QlikAbout' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\Qlik-Cli.psm1:150 char:19

I installed Qlik-Cli manually by downloading the zip file and copying into the powershell modules folder.

Am I missing something here?

Thanks

**Comment by ryanplkam** [comment]
Issue was resolved by running powershell as administrator.

**Comment by Nillth** [comment]
This should not need to be run with Administrator privileges.
I would check that the ntfs permissions to ensure that the user account has at least read access to "C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\"
