### ISSUE TITLE
How to create a User Directory connection to a SQL database

### ISSUE THREAD

**Issue by LennonHoover** [ahaydon/Qlik-Cli-Windows#128]
Hi guy's,

I'm trying to automate (in powershell) creating a user directory connector to a SQL database using the New-QlikUserDirectory command. I cant seem to get it to work. Am i using the correct command? what are the parameters for user table, attribute user table, connection string etc......Any help will be greatly appreciated. Thx!

**Comment by levi-turner** [comment]
Do you have a working UDC outside of Qlik-CLI? I ask because the actual values are obviously dependent on working values coming in. This is running fine on my end (with known good values):

```powershell
@(
[pscustomobject]@{name='Users table'; value='public.users_basic'},
[pscustomobject]@{name='Attributes table'; value='public.attributes_basic'}, 
[pscustomobject]@{name='Connection string part 1'; value='Driver={PostgreSQL ANSI(x64)};Server=localhost;Port=4432;Database=QlikUsers;uid=postgres;pwd=<mySecretPassword>;'}, 
[pscustomobject]@{name='User directory name'; value='psql'}
)

New-QlikUserDirectory -name PostgreSQL -userDirectoryName PSQL -type "Repository.UserDirectoryConnectors.ODBC.ODBC" -settings $settings
```

**Comment by LennonHoover** [comment]
Hi, Yes i have a working UDC connection outside of Qlik-CLi.
My working UDC connection, connects to a SQL database.

I'm trying to automate this so when i build a new QS env i can run this script to create the UDC connection

**Comment by Nillth** [comment]
The following will build out the full Json that needs to be supplied to the API

```
#region Modify these values
$UDCName = "UDCNamex"
$UserDirectoryName = "UserDirectoryNamex"
$UsersTable = "TableNameUsers"
$AttributeTableName = "TableNameAttributes"
$ConnectionString = "Driver={SQL Server Native Client 10.0};Server=.\\SQLEXPRESS;Database=Test;Trusted_Connection=yes;"
$ENCConnectionString = ""
$SyncOnlyLoggedInUsers = $true
#endregion No modification required after this.

$JsonODBC = @"
{
  "name": "$($UDCName)",
  "type": "Repository.UserDirectoryConnectors.ODBC.OdbcSql",
  "syncOnlyLoggedInUsers": $SyncOnlyLoggedInUsers,
  "settings": [
    {
      "name": "User directory name",
      "category": "",
      "secret": false,
      "value": "$($UserDirectoryName)"
    },
    {
      "name": "Users table",
      "category": "",
      "secret": false,
      "value": "$($UsersTable)"
    },
    {
      "schemaPath": "UserDirectory.Settings",
      "name": "Attributes table",
      "category": "",
      "secret": false,
      "value": "$($AttributeTableName)"
    },
    {
      "name": "Connection string part 1",
      "secret": false,
      "value": "$($ConnectionString)"
    },
    {
      "name": "Connection string part 2 (secret)",
      "secret": true,
      "value": "$($ENCConnectionString)"
    },
    {
      "schemaPath": "UserDirectory.Settings",
      "name": "Synchronization timeout in seconds",
      "userDirectorySettingType": 1,
      "secret": false,
      "value": "240"
    }
  ],
  "tags": [],
  "creationType": 1
}
"@
Invoke-QlikPost "/qrs/userdirectory" -Body $JsonODBC
```

**Comment by LennonHoover** [comment]
Thx Nillth much appreciated!
When I run the code you provided via powershell, i amended the variables according however i get the following error :
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.19.2\functions\core.ps1:62 char:19
+         $result = Invoke-RestMethod @paramInvokeRestMethod @params
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by Nillth** [comment]
the provided code works as is. I can only assume that something in the values you have changed is incorrect?
are you able to provide the code you are using?

**Comment by Nillth** [comment]
stale
