### ISSUE TITLE
Issue exporting large apps (again)

### ISSUE THREAD

**Issue by mountaindude** [ahaydon/Qlik-Cli-Windows#129]
Seems the issue from 2019 (#83) which prevented >2GB apps from being exported has resurfaced. 
Using most recent version (1.19.2), the app export fails for large apps.
Seems the only call in functions/core.ps1 is Invoke-RestMethod, which fails (always?) for large files. The previous solution was to call Invoke-WebRequest instead.

Or is there another way these days to export large apps?

**Comment by levi-turner** [comment]
I don't have cycles to dig into a fix, but this is the trace on my end:
```
PS C:\> Export-QlikApp -id b7913ff2-2294-411c-a998-41f472e54359
Stream was too long.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.19.2\functions\core.ps1:62 char:19
+         $result = Invoke-RestMethod @paramInvokeRestMethod @params
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by mountaindude** [comment]
Mmm I am pretty swamped too, still wanted to report it. And good that you could confirm it, Levi.
Things might ease up in a few weeks. Maybe.

**Comment by levi-turner** [comment]
Is that the same exception that you're seeing? My environment involves two servers sitting beside themselves so just want to make sure for @ahaydon (or maybe @Nillth ) who are gurus of the Qlik-Cli code have the right direction. Or myself if I get cycles in a bit to look in more depth.

**Comment by mountaindude** [comment]
Looks like the same error, yes.

```
PS E:\temp> Export-QlikApp -id 002e077a-4701-455b-b1b5-b940b9583b40
Invoke-RestMethod : Stream was too long.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:62 char:19
+         $result = Invoke-RestMethod @paramInvokeRestMethod @params
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

PS E:\temp>
```
