### ISSUE TITLE
Getting the script log in the standard output

### ISSUE THREAD

**Issue by hammamr** [ahaydon/Qlik-Cli-Windows#130]
Hello,

Using the command below:
Start-QlikTask "Reload Operations Monitor" -wait | Wait-QlikExecution

Is it possible to get the script log in the standrad output ?
In the output we have the path to the script log file but we don't have the content of the log file.
How to send the content of the log file to the standard output ?

Thanks
Sidi

**Comment by ahaydon** [comment]
You can use something like this to download the log file.
```
$result = Start-QlikTask "Reload Operations Monitor" -wait | Wait-QlikExecution
$ticket = Invoke-QlikGet "/qrs/reloadTask/$($result.taskID)/scriptlog?filereferenceid=$($result.filereferenceid)"
Invoke-QlikDownload "/qrs/download/reloadtask/$ticket/$($result.taskID).log" "$($result.taskID).log"
```
You could probably replace the final Invoke-QlikDownload with Invoke-QlikGet to output to console instead of saving to a file.

**Comment by hammamr** [comment]
Hello,

Thanks for the answer, I have tested it, the first two commands work fine.
However, I have the following error message when executing the command to download the log file or to output the log to the console.

PS C:\Users\qqsens00> $result = Start-QlikTask "Restitutions_Batch_LV2_Cobol" -wait | Wait-QlikExecution
PS C:\Users\qqsens00> $ticket = Invoke-QlikGet "/qrs/reloadTask/$($result.taskID)/scriptlog?filereferenceid=$($result.filereferenceid)"
PS C:\Users\qqsens00> Invoke-QlikDownload "/qrs/download/reloadtask/$ticket/$($result.taskID).log" "$($result.taskID).log"
Invoke-RestMethod : Le serveur distant a retourné une erreur : (404) Introuvable.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

PS C:\Users\qqsens00> Invoke-QlikGet "/qrs/download/reloadtask/$ticket/$($result.taskID).log" "$($result.taskID).log"
Invoke-RestMethod : Le serveur distant a retourné une erreur : (404) Introuvable.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

PS C:\Users\qqsens00>

Best Regards
Sidi

**Comment by ahaydon** [comment]
It looks like the download ID is returned in a parameter called value, so the last command should be:
`Invoke-QlikDownload "/qrs/download/reloadtask/$($ticket.value)/$($result.taskID).log" "$($result.taskID).log"`

**Comment by hammamr** [comment]
Thanks, the download works fine, but I still have an error when writing the log to the console:

PS C:\Users\qqsens00> $result = Start-QlikTask "Restitutions_Batch_LV2_Cobol" -wait | Wait-QlikExecution
PS C:\Users\qqsens00> $ticket = Invoke-QlikGet "/qrs/reloadTask/$($result.taskID)/scriptlog?filereferenceid=$($result.filereferenceid)"
PS C:\Users\qqsens00> Invoke-QlikDownload "/qrs/download/reloadtask/$($ticket.value)/$($result.taskID).log" "$($result.taskID).log"
PS C:\Users\qqsens00> Invoke-QlikGet "/qrs/download/reloadtask/$($ticket.value)/$($result.taskID).log" "$($result.taskID).log"
Invoke-RestMethod : Le serveur distant a retourné une erreur : (400) Demande incorrecte.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

PS C:\Users\qqsens00>

**Comment by ahaydon** [comment]
the ticket is one-time use, either use Get or Download, not both. If you want to save to disk and display on console then use Get-Content to read the file once it is downloaded rather than downloading twice.

Also, the second parameter to Invoke-QlikGet is a filter rather than a filename, so the filename is being interpreted as a filter and so is invalid.

**Comment by hammamr** [comment]
It works, thanks again for your responsiveness.

**Comment by hammamr** [comment]
Hello,

I'm not able to manage correctly the return code of task execution.
I wrote a powershell script with the following content.
The return code is always 0 even if the task excution fails.
I tested also with a non existing task name, and the return code is always 0.
Any idea ?

Connect-Qlik server.intra
$result = Start-QlikTask "task_name" -wait | Wait-QlikExecution
$Code_Retour=$LASTEXITCODE
Write-Output "code retour $Code_Retour"
Write-Output $result
$ticket = Invoke-QlikGet "/qrs/reloadTask/$($result.taskID)/scriptlog?filereferenceid=$($result.filereferenceid)"
Invoke-QlikGet "/qrs/download/reloadtask/$($ticket.value)/$($result.taskID).log"
exit $Code_Retour

Here is the log printed to the console for non existing task name:
buildVersion      : 26.4.3.0
buildDate         : 11/27/2019 14:26:49 PM
databaseProvider  : Devart.Data.PostgreSql
nodeType          : 1
sharedPersistence : True
requiresBootstrap : False
singleNodeOnly    : False
schemaPath        : About

Invoke-RestMethod : Le serveur distant a retourné une erreur : (400) Demande incorrecte.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Wait-QlikExecution : Impossible de lier l'argument au paramètre « executionId », car il s'agit d'une chaîne vide.
Au caractère D:\applis\vqsens\pur\trt\qsense.z.batch.ps1:2 : 75
+ ... k "Restitutions_pff_Batch_LV2_Cobol_myt16" -wait | Wait-QlikExecution
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData : (:) [Wait-QlikExecution], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Wait-QlikExecution

code retour 0
Invoke-RestMethod : Le serveur distant a retourné une erreur : (404) Introuvable.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : Le serveur distant a retourné une erreur : (404) Introuvable.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by ahaydon** [comment]
The $LASTEXITCODE variable is used for Win32 console applications only, it does not apply to PowerShell commands.

Some of the ways you can handle errors in PowerShell are:
- $err variable contains all errors during the session
- Use the `-ErrorVariable` on a command to store errors in a variable
- Set the `-ErrorAction Stop` and use try...catch to handle the error
- Set the variable `$ErrorActionPreference='Stop'` to stop on all errors and use try...catch

**Comment by hammamr** [comment]
Hello,

Finally I used try / catch and it works, thanks.

**Comment by Nillth** [comment]
stale
