### ISSUE TITLE
Intermittent issue when connecting to QS server

### ISSUE THREAD

**Issue by dennisate** [ahaydon/Qlik-Cli-Windows#131]
I'm running the powershell command on the QS central node from a Control M job and it fails intermittently.  Any idea why?  I have no issues running this from my local desktop.  <I've provided a dummy IP address below>

Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
Import-Module Qlik-Cli
Connect-Qlik -verbose -Computername https://10.11.111.11 -TrustAllCerts -UseDefaultCredentials

VERBOSE: No valid certificate found, using Windows credentials
VERBOSE: Raw output: 
VERBOSE: Adding header x-Qlik-Xrfkey: wntciuvztxqbrhaz
VERBOSE: Calling Get for https://10.11.111.11/qrs/about?xrfkey=wntciuvztxqbrhaz
VERBOSE: GET https://10.11.111.11/qrs/about?xrfkey=wntciuvztxqbrhaz with 0-byte payload
**Invoke-RestMethod : The request was aborted: The request was canceled.**
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:63 char:19
         $result = Invoke-RestMethod @paramInvokeRestMethod @params
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
 FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

I'm already using the latest Qlik CLI version.

Thanks and regards,

Dennis

**Comment by ahaydon** [comment]
Is Control M running on a Windows machine in the same domain as the Qlik Sense server?

The -UseDefaultCredentials option uses the Windows credentials of the user running the command, so that user needs to be able to authenticate to Sense. Otherwise you will need to use certificates to authenticate.

**Comment by dennisate** [comment]
The Control M agent is already running on the QlikSense Central node and using a service account on the same domain as the one used by QlikSense.  I ran 20 jobs yesterday out of which 2 failed with the error reported above.  If it's an authentication issue, wouldn't it return a different error message and fail all the time?

**Comment by Nillth** [comment]
Stale
