### ISSUE TITLE
Updating certificate thumbprint after certificate update

### ISSUE THREAD

**Issue by mcdado** [ahaydon/Qlik-Cli-Windows#132]
Hello, I set up [win-acme](https://github.com/win-acme/win-acme) and [my hooks for OVH DNS challenge](https://github.com/mcdado/win-acme-dns-ovh) to get a certificate for our server that is inside a LAN (http auth is not possible). This way I can get automatic renewals from Let's Encrypt.

I added `powershell.exe` as a script to run after renewal, with this arguments: `Update-QlikProxy -id [my-node-id] -SslBrowserCertificateThumbprint {CertThumbprint}` as parameters.

My questions are:

- does this restart the proxy in a way that the certificate is reloaded?
- is there a better way than to include the proxy id, for example getting the first one?

**Comment by levi-turner** [comment]
> does this restart the proxy in a way that the certificate is reloaded?

Yes

> is there a better way than to include the proxy id, for example getting the first one?

I guess, it depends. If you know the Proxy Service ID, then no. If you don't know the proxy service ID then you'd need something like:
```
$nodeName = 'Central'
$(Get-QlikProxy -filter "serverNodeConfiguration.name eq '$($nodeName)'").id
```
Of course you should be able to slam things together with inlines as needed for example (not tested):

```
$nodeName = 'Central'
Update-QlikProxy -id $(Get-QlikProxy -filter "serverNodeConfiguration.name eq '$($nodeName)'").id -SslBrowserCertificateThumbprint {CertThumbprint}
```

**Comment by mcdado** [comment]
Thank you, that's good to know!
