### ISSUE TITLE
Connection fails when executed by TWS scheduler

### ISSUE THREAD

**Issue by hammamr** [ahaydon/Qlik-Cli-Windows#134]
Hello,

I have the following powershell script.
When I excute it manually from powershell command line with QlikSense service account it works fine.
But when it is executed by the enterprise scheduler (TWS) it fails with the following error.
TWS doesn't use QlikSense service account, it it uses an other local account wich is a member of the local administrators group and has the QlikSense role ContentAdmin.
I also added TWS user to the groupe "QlikSense service users" but I still have the same error (unauthorized error 401) when connecting to the server.

Any idea to get it working from TWS scheduler ?

Thanks.

```
$task = $args[0]
Write-Output $tache
$heureDebutConn=Get-Date -Format G 
Write-Output "###############  $heureDebutConn : Connexion au moteur QlikSense  ###############"
$connexion=Connect-Qlik myserver.intra
$heureFinConn=Get-Date -Format G 

if ($connexion -eq $null) {
	Write-Output "$heureFinConn : Impossible de se connecter au moteur Qlik"
	exit 1
} else {
	Write-Output "$heureFinConn : Connexion OK au moteur QlikSense"
}

$heureDebutVerif=Get-Date -Format G 
Write-Output "###############  $heureDebutVerif : vérification si la tâche QlikSense existe  ###############"
$tache=Get-QlikTask -filter "name eq '$task'"
$heureFinVerif=Get-Date -Format G 
if ($tache -eq $null) {
	Write-Output "$heureFinVerif : La tâche QlikSense n'existe pas"
	exit 2
} else {
	Write-Output "$heureFinVerif : La tâche QlikSense existe et sera executée"
}

$heureDebutExec=Get-Date -Format G 
Write-Output "###############  $heureDebutExec : Début exécution de la tâche QlikSense  ###############"

$result = Start-QlikTask $task -wait | Wait-QlikExecution

$heureFinExec=Get-Date -Format G 

if ($result -eq $null) {
	Write-Output "$heureFinExec : Erreur lors de l'exécution de la tâche QlikSense"
	exit 100
} 
 elseif ($($result).status -eq "FinishedSuccess") {
	Write-Output "$heureFinExec : Execution OK de la tâche QlikSense"
	Write-Output $result
	$ticket = Invoke-QlikGet "/qrs/reloadTask/$($result.taskID)/scriptlog?filereferenceid=$($result.filereferenceid)"
	Invoke-QlikGet "/qrs/download/reloadtask/$($ticket.value)/$($result.taskID).log"
	exit 0
}
else {
	Write-Output "$heureFinExec : Execution KO de la tâche QlikSense"
	Write-Output $result
	$ticket = Invoke-QlikGet "/qrs/reloadTask/$($result.taskID)/scriptlog?filereferenceid=$($result.filereferenceid)"
	Invoke-QlikGet "/qrs/download/reloadtask/$($ticket.value)/$($result.taskID).log"
	exit 101
}
```

This is the error message when the script is executed in batch mode with TWS scheduler:

> ###############  01/10/2020 17:33:51 : Connexion au moteur QlikSense  ###############
> Invoke-RestMethod : Le serveur distant a retourn une erreur▒: (401) Non autoris.
> Au caractre C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:29 : 15
> + ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Ses ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebEx
>    ception
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> 
> Invoke-RestMethod : La demande a t abandonne▒: La demande a t annule.
> Au caractre C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
> + ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebEx
>    ception
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> 
> Get-Member : Vous devez spcifier un objet pour l'applet de commande Get-Member.
> Au caractre C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\helper.ps1:7 : 30
> + ...  $Script:enums = $enums | Get-Member -MemberType NoteProperty | forea ...
> +                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : CloseError : (:) [Get-Member], InvalidOperationException
>     + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
> 
> Invoke-RestMethod : Le serveur distant a retourn une erreur▒: (401) Non autoris.
> Au caractre C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
> + ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebEx
>    ception
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> 
> 01/10/2020 17:33:55 : Impossible de se connecter au moteur Qlik
> Code retour: 1 Traitement KO - Fin: 01/10/2020 17:33:55
>

**Comment by Nillth** [comment]
the issue appears to be a failure to connect. depending on how TWS handles the user credentials you could try the following
`$connexion=Connect-Qlik myserver.intra -TrustAllCerts -UseDefaultCredentials`

**Comment by hammamr** [comment]
Hello,

I tried with `$connexion=Connect-Qlik myserver.intra -TrustAllCerts -UseDefaultCredentials`
But it fails in both TWS and manually from Power Shell command line with the following error message:

> PS D:\applis\qqsens\pur\trt> .\qsense.z.batch.ps1 Chargement_pff_Batch_LV2_Cobol_myt162
> ###############  05/10/2020 10:37:27 : Connexion au moteur QlikSense  ###############
> Invoke-RestMethod : Le serveur distant a retourné une erreur : (401) Non autorisé.
> Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:29 : 15
> + ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Ses ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> 
> 05/10/2020 10:37:27 : Impossible de se connecter au moteur Qlik
> PS D:\applis\qqsens\pur\trt>

**Comment by Nillth** [comment]
> erreur : (401) Non autorisé

means that the service account is unable to authenticate to the Qlik sense server. 

You said that TWS is running as a local account? 
> TWS doesn't use QlikSense service account, it it uses an other local account

is the account local on the Qlik Sense server or on a different server?

have you tried Certificate based authentication?

[Establishing-a-connection](https://github.com/ahaydon/Qlik-Cli-Windows/wiki/Establishing-a-connection)

**Comment by hammamr** [comment]
Hello,

Yes, TWS is using a local user on the local server where QlikSense is runnig.
Finally it works with certifiate, I exported Qlik certificate from QMC with secrt key and without password.
Then I copied client.pfx in a local directory, then I used the following command and it works fine:

`$connexion=Get-PfxCertificate D:\client.pfx | Connect-Qlik myserver.intra`

Note that if I export the certificate with a password, the command asks for the password, so doesn't work with TWS in batch mode, that's why i exported it witout password.

However I have an other issue, in the begening of my script i check if the task passed in parameter exists or not.
The problem is tha the following command is not case sensitive:
`$tache=Get-QlikTask -filter "name eq '$task'"`

And this one is cas sensitive:
`$result = Start-QlikTask $task -wait | Wait-QlikExecution`

Is it possible to make Get-QlikTask -filter "name eq '$task'"` a case sensitive ??
I tried with c option but it doesn't work (Get-QlikTask -filter "name ceq '$task'"`).

For exemple I have a task named "Test" in QMC:

> PS D:\applis\qqsens\pur\trt> Get-QlikTask -filter "name eq 'Test'"
> 
> nextExecution    status       name lastExecution
> -------------    ------       ---- -------------
> 1753/01/01 01:00 FinishedFail Test 2020/10/07 12:10
> 
> 
> PS D:\applis\qqsens\pur\trt> Get-QlikTask -filter "name eq 'test'"
> 
> nextExecution    status       name lastExecution
> -------------    ------       ---- -------------
> 1753/01/01 01:00 FinishedFail Test 2020/10/07 12:10


PS D:\applis\qqsens\pur\trt>

> PS D:\applis\qqsens\pur\trt> Start-QlikTask test
> Invoke-RestMethod : Le serveur distant a retourné une erreur : (400) Demande incorrecte.
> Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 : 15
> + ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> 
> PS D:\applis\qqsens\pur\trt> Start-QlikTask Test
> 
> PS D:\applis\qqsens\pur\trt>

**Comment by Nillth** [comment]
Stale
