### ISSUE TITLE
Update status for task trigger

### ISSUE THREAD

**Issue by kmarnold24** [ahaydon/Qlik-Cli-Windows#135]
I've been reading the trigger docs and we can build complete schema event based triggers for tasks but it doesn't appear there is a way to enable or disable the triggers via CLI.  We are looking for a way to keep the triggers stored on the task but enable them all or disable them by using tags and CLI.  Does something like that exist using existing framework?

**Comment by ahaydon** [comment]
There's no `Update-QlikSchemaEvent` (or CompositeEvent) yet but it can still be done, something like the following should work.

```powershell
$triggers = Invoke-QlikGet /qrs/schemaEvent -filter "tags.name eq 'SomeTag'"
$triggers | ForEach-Object {
    $_.enabled = $false
    $json = $_ | ConvertToJson -Compress -Depth 10
    Invoke-QlikPut "/qrs/schemaEvent/$($_.id)" $json
}
```

**Comment by kmarnold24** [comment]
Thanks for the reply.  I loaded this up and I don't know if we can filter on schema event tags because they don't actually have them.  Is the filter looking up at the task level?  I did something like this.  I can get the right task, but it doesn't like the PUT.  Plus I think it puts the focus of the enabled parameter on the Task level and not Trigger level
```
$triggers = Invoke-QlikGet /qrs/reloadtask -filter "tags.name eq 'SomeTag'"
$triggers | ForEach-Object {
    $_.enabled = $false
    $json = $_ | ConvertTo-Json -Compress -Depth 10
    Invoke-QlikPut "/qrs/schemaEvent/$($_.id)"$json
```
However the Qlik Updating a Schema Event page says to reference qrs/reloadtask/update call to update schema events.  So I thought I was close, but now I am not so sure.

**Comment by ahaydon** [comment]
You're right, the filter should have been `reloadTask.tags.name eq 'SomeTag'`. This will return all schema events associated with a task with the specified tag.

There are a couple of ways of updating tasks and triggers, you can use the bundle that allows updating the task and its associated triggers in a single call, but you can also update the triggers on their own. Check the API reference for details of all the available endpoints https://help.qlik.com/en-US/sense-developer/September2020/APIs/RepositoryServiceAPI/index.html?page=9

**Comment by Nillth** [comment]
Stale
