### ISSUE TITLE
Should we remove the dependency to IE?

### ISSUE THREAD

**Issue by vbakke** [ahaydon/Qlik-Cli-Windows#136]
We suddenly got this message:
![image](https://user-images.githubusercontent.com/4437745/97003182-5946d480-153b-11eb-9b8f-5f1db3060dff.png)

We found a solution on StackOverflow:
https://stackoverflow.com/questions/38005341/the-response-content-cannot-be-parsed-because-the-internet-explorer-engine-is-no

Our solution was to start IE. 😆 

But it might be better to user the `-UseBasicParsing` on `Invoke-WebRequest` in `core.ps1`
Just as a suggestion. :)

**Comment by ahaydon** [comment]
I'm not able to reproduce this issue. I built a new server and ran `Import-QlikApp` and it completed successfully, I then opened IE and the setup prompt appeared.

Can you provide some details of the OS and PowerShell version please?

Does it just fail on file transfers or do other API calls result in the same error? Non file transfers use the `Invoke-RestMethod` command.

**Comment by vbakke** [comment]
Hmm.. I've never had this problem before either. But I have normally open IE before I start Qlik-CLI, so I can't be sure how frequent this is. (Need IE to download Chrome, you know. : )

This server is (from 'systeminfo'):
OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763

$PSVersionTable:
PSVersion                      5.1.17763.1490                                                                                        
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.17763.1490                                                                                       
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1

**Comment by ahaydon** [comment]
I can reproduce on PS4 but not on PS5.1, only a slight difference in version 5.1.17763.1007.

It's weird but at least I can reproduce and test a fix.
