### ISSUE TITLE
Export-Import not working well

### ISSUE THREAD

**Issue by itsik85** [ahaydon/Qlik-Cli-Windows#140]
Hi,

I wrote a script in PowerShell that export a model from one server and import it to another server (using certificates).
The process worked fine for me with a sample model, but when I tried to move a real model with data, two problems occurred:

1. It passed me only one sheet out of two
2. It didn't pass the Master-Items!

I would appreciate your help,
Isaac

**Comment by Nillth** [comment]
Stale
