### ISSUE TITLE
Start-QlikTask fails with task of type "User Synchronization"

### ISSUE THREAD

**Issue by hammamr** [ahaydon/Qlik-Cli-Windows#142]
Hello,

I use the Cmdlet Start-QlikTask to run QlikSense Tasks.
It works fine for "Reload" tasks, but for "User Synchronization" task it fails with the following error.
Note that the task is executed correctly in the QMC but the Cmdlet fails.

Is it normal ?

> PS D:\> Start-QlikTask connection_postgre_odbc_usersynctask -wait | Wait-QlikExecution
> Invoke-RestMethod : Le serveur distant a retourné une erreur : (400) Demande incorrecte.
> Au caractère C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:66 : 23
> + ...            $result = Invoke-RestMethod @paramInvokeRestMethod @params
> +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Best Regards
Sidi

**Comment by Nillth** [comment]
Stale
