### ISSUE TITLE
New-QlikTaskSchedule always fails with "Unable to create Reload Task event"

### ISSUE THREAD

**Issue by marvinmai** [ahaydon/Qlik-Cli-Windows#143]
Hi,
for me the call of New-QlikTaskSchedule always fails. I get the following error message: 

> 
> New-QlikTaskSchedule : Unable to create Reload Task event
> At D:\iTAC.BI.Service.Qlik\01_Qlik\QlikSenseStorage\setup.ps1:92 char:9
>          New-QlikTaskSchedule -Repeat Monthly -Name "Every month" -Day ...
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>      FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-QlikTaskSchedule
>  
> Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
> At D:\iTAC.BI.Service.Qlik\Installation\qlik-cli\functions\core.ps1:62 char:19
>          $result = Invoke-RestMethod @paramInvokeRestMethod @params
>                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
>      FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

I debugged into task.ps1 where New-QlikTaskSchedule is defined and tracked it down to line 425 where the error has to occur. Here you can see the content of $TaskEvent in line 424 right before the error occurs. I have no idea why this happens. 

![image](https://user-images.githubusercontent.com/29154212/100384725-22277f80-3021-11eb-968f-c09d6b332391.png)

This is $json right before the call of Invoke-QlikPost fails: 
```
{
    "name": "Every month",
    "timezone": "UTC",
    "daylightSavingTime": 1,
    "startDate": "",
    "expirationDate": "",
    "schemaFilterDescription": [
        "* * - * * 1 * *"
    ],
    "incrementDescription": "0 0 1 0",
    "incrementOption": 1,
    "Integer": null,
    "reloadTask": {
        "id": "324b485d-6d57-4641-8dea-cd57607c64e9",
        "operational": {
            "id": "d8aa8fa2-7d13-4695-b66e-929bc8dce68c",
            "lastExecutionResult": {
                "id": "017a17fb-14f4-437d-8cf9-5c7c8fcaed27",
                "executingNodeName": "",
                "status": 0,
                "startTime": "1753-01-01T00:00:00.000Z",
                "stopTime": "1753-01-01T00:00:00.000Z",
                "duration": 0,
                "fileReferenceID": "00000000-0000-0000-0000-000000000000",
                "scriptLogAvailable": false,
                "details": [],
                "scriptLogLocation": "",
                "scriptLogSize": -1,
                "privileges": null
            },
            "nextExecution": "1753-01-01T00:00:00.000Z",
            "privileges": null
        },
        "name": "Task Historic Incremental Extractor",
        "taskType": 0,
        "enabled": true,
        "taskSessionTimeout": 1440,
        "maxRetries": 0,
        "privileges": null
    },
    "userSyncTask": "",
    "externalProgramTask": ""
}
```

Can you maybe explain why this error occurs? I fear this is a bug but can't say for sure.

**Comment by marvinmai** [comment]
we found a solution for that: 
in the file task.ps1, function New-QlikTaskSchedule we exchanged the lines
```
[string]$StartDate = $($StartDate.GetDateTimeFormats()[97])
[string]$expirationDate = $expirationDate.GetDateTimeFormats()[97]
```
with 
```
[string]$StartDate = '{0:yyyy-MM-ddThh:mm:ss.fffZ}' -f $StartDate
[string]$expirationDate = '{0:yyyy-MM-ddThh:mm:ss.fffZ}' -f $expirationDate
```
and now it's working fine. I guess this has to be fixed.

**Comment by ahaydon** [comment]
I can't find the lines of code referenced anywhere in the module, the closest match I can find it the following lines at 321/322 in resources/task.ps1:

```powershell
    [string]$StartDate = $startDate.ToString("yyyy-MM-ddTHH:mm:ss.000Z");
    [string]$expirationDate = $expirationDate.ToString("yyyy-MM-ddTHH:mm:ss.000Z");
```

This already formats the dates as described so I do not think there is a bug here, unless more details can be provided.

**Comment by Nillth** [comment]
I think this was present in a Development Branch when I first wrote the function. I it was subsequently fixed before being merged into main.
