### ISSUE TITLE
app reload not always correct

### ISSUE THREAD

**Issue by hvdbunte** [ahaydon/Qlik-Cli-Windows#145]
Hi,

We try to automatically publish apps to different streams. So we change a variable in the app and reload and publish/switch the app to a different stream. 
So everything works except the reload command:

    $computerName="qlik-test.xxx.xx"
    $computerPort="4747"
    $userDirectory="QLIK-TEST"
    $userName=""
    $uri = "wss://$($computerName):$($computerPort)"

    Connect-Qlik -TrustAllCerts

    $location = [Qlik.Engine.Location]::FromUri($uri)
    [Qlik.Engine.LocationExtensions]::AsDirectConnection($location,$userDirectory,$userName)

    $AppIdentifiersByID = [Qlik.Engine.LocationExtensions]::AppWithId($location,$newappToPublishid)

    $QEApp = Qlik.Engine.LocationExtensions]::App($location,$AppIdentifiersByID,$Session,$NoData)

    $DoReloadExParams = [Qlik.Engine.DoReloadExParams]::new()
    $QEApp.DoReloadEx($DoReloadExParams)

Or I tried:
`Invoke-QlikPost -path "/qrs/app/$($appsToPublish.id)/reload"`

When I try this and see the script log folder it reloaded correctly but when I look inside the app it isn’t reloaded correctly. It contains a value from an earlier stream. 

Any idea what I need to use to reload correctly?

Kind Regards,
Hvdbunte

**Comment by Nillth** [comment]
it looks like you are mixing the [Qlik Sense .NET SDK](https://help.qlik.com/en-US/sense-developer/csh/Subsystems/NetSDKAPI/Content/Sense_NetSDKAPI/Introduction/Net-Sdk-Libraries.htm) & Qlik-CLI-Windows
and this isn't really the forum for troubleshooting the Qlik Sense .Net SDK

having said that, using the Qlik Sense .Net SDK to perform the reload does not update reload time in the QRS Repository Metadata, for that you need to perform the reload using the QRS APIs which can be done with Qlik-CLI-Windows.

as you have not provided where you are setting the variable `$appsToPublish` I assume that it is holding more than one app as it is **apps**ToPublish (plural) in which case you will need to run it in a loop.

```PowerShell
foreach ($app in $appsToPublish){
    Invoke-QlikPost -path "/qrs/app/$($app.id)/reload"
}
```

so a working example the following will get all apps in the Everyone Stream that have not been reloaded in the past 24 hours and perform a reload on them.

```PowerShell
Connect-Qlik -TrustAllCerts
$StreamName = "Everyone"
$QSappsInEveryone = Get-QlikApp -filter "Stream.Name eq '$($StreamName)' and lastReloadTime lt '$($(Get-Date).AddHours(-24).ToString('yyyy-MM-ddTHH:mm:ss.000Z'))'" 
foreach ($app in $QSappsInEveryone){
    Invoke-QlikPost -path "/qrs/app/$($app.id)/reload"
}
```

**Comment by Nillth** [comment]
Stale
