### ISSUE TITLE
Sample post for reload single task with Certificate from a different server

### ISSUE THREAD

**Issue by didierodayo** [ahaydon/Qlik-Cli-Windows#149]
I am looking for an example of Task reload query using CLI where the .ps1 file can be triggered from a different server using the Qlik sense server  certificate and NT username.

Thanks

**Comment by Nillth** [comment]
The wiki pages show an example of how you can do this this process

The [Advanced-usage](https://github.com/ahaydon/Qlik-Cli-Windows/wiki/Advanced-usage) page literally shows and example of how to connect using a Certificate to a remote server ```Get-PfxCertificate .\qlikserver01-client.pfx | Connect-Qlik -ComputerName qlikserver01.domain.ad -UserName INTERNAL\sa_api -TrustAllCerts``` and a little further down how to run reload tasks ```Get-QlikReloadTask -filter "app.stream.name eq 'Monitoring Apps'" | Start-QlikTask -Wait | Wait-QlikExecution```

both of these examples can be adapted to suite your situation

```
Get-PfxCertificate "C:\pathto\qlikserver01-client.pfx" | Connect-Qlik -ComputerName qlikserver01.domain.ad -UserName "$($env:USERDOMAIN)\$($env:USERNAME)" -TrustAllCerts
Get-QlikReloadTask -filter "app.stream.name eq 'StreamName'" | Start-QlikTask -Wait | Wait-QlikExecution
#or 
Get-QlikReloadTask -filter "name eq 'ReloadTaskName'" | Start-QlikTask -Wait | Wait-QlikExecution
#or 
Get-QlikReloadTask -filter "app.name eq 'AppName'" | Start-QlikTask -Wait | Wait-QlikExecution

```
