### ISSUE TITLE
Export-QlikApp still failes to export large apps

### ISSUE THREAD

**Issue by RBI-Mike** [ahaydon/Qlik-Cli-Windows#150]
Duplicate of #129 

Fixed in v1.20.0 that has just been released.

_Originally posted by @ahaydon in https://github.com/ahaydon/Qlik-Cli-Windows/issues/137#issuecomment-718023071_

**Comment by RBI-Mike** [comment]
Hi there,
I've tried with versions 1.20.0 and 1.21.0 but still facing this error message when exporting large (>2GB) files.

The qvf files is downloaded to QlikSense's temp content (C:\ProgramData\Qlik\Sense\Repository\TempContent) in seconds, but after around 70 seconds this error occurs.

I'm using Powershell v4.

Do you have any advice?

Thanks,
Mike

_Invoke-WebRequest : Stream was too long.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:60 
char:23
+             $result = Invoke-WebRequest @paramInvokeRestMethod @params 
-UseBasic ...
+                       
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOExcepti 
   on
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Comma 
   nds.InvokeWebRequestCommand_

**Comment by ahaydon** [comment]
PowerShell v4 limitation
