### ISSUE TITLE
New-QlikCustomProperty Only Single Value

### ISSUE THREAD

**Issue by V1NW** [ahaydon/Qlik-Cli-Windows#152]
We have created a script to bulk create multiple choice values in one name as Stream.

But only the first value in the list can be created in Custom Property.

**Comment by ahaydon** [comment]
You can provide multiple choice values when creating the property, the following will create a Group property with the choices of 'A' and 'B'.

```powershell
New-QlikCustomProperty -name Group -objectTypes Stream -choiceValues 'A', 'B'
```

**Comment by V1NW** [comment]
Thank you @ahaydon 

This script is working.

Before that, we are using the loop to set each -choiceValues but it can only update as the first record.

Thanks again.

Best Regards,
Vincent Wei
