### ISSUE TITLE
Nature of Connect-Qlik command in Qlik-Cli module

### ISSUE THREAD

**Issue by Ankit-K-Gupta** [ahaydon/Qlik-Cli-Windows#153]
Hi Adam,

first of all, thanks for creating this wonderful set of commands. It has made life so easy for me. I have used it to automate some really tedious tasks which were  very time consuming.
My query here is, whether the Connect-Qlik command uses proxy service (or virtual proxy) to connect to Qlik Sense repository. Or it establishes a direct connection with Qlik Sense repository database and the other commands e.g. import-app, export-app etc directly go to repository database). Also, can you please suggest, how long the connection/session will remain active/alive once the Connect-Qlik command is used.

Regards
Ankit

**Comment by levi-turner** [comment]
> whether the Connect-Qlik command uses proxy service (or virtual proxy) to connect to Qlik Sense repository. Or it establishes a direct connection with Qlik Sense repository database and the other commands e.g. import-app, export-app etc directly go to repository database).

Either can be done. See https://github.com/ahaydon/Qlik-Cli-Windows/wiki/Establishing-a-connection

**Comment by Nillth** [comment]
https://github.com/ahaydon/Qlik-Cli-Windows/issues/153#issuecomment-819945694
