### ISSUE TITLE
QS Trigger to more than one environment from client server. 

### ISSUE THREAD

**Issue by Sandheep33** [ahaydon/Qlik-Cli-Windows#154]
Hi,
I am using Qlik-cli to trigger the QS tasks from a single client server. That's working fine now, no issues.

Here I need to add one more QS environment and trigger the QS tasks from the same Client server.  I have imported both server certificates and tried out the same steps. But it connects to only one environment and other one is failing. The connection is working to new environment When I removed the old one.  So the problem is that couldn't connect the more than one environment. Could you please suggest here, how to connect more than one QS environment using Qlik-cli from a Client server?

Error log : 

PS C:\Windows\system32> connect-qlik -Verbose
VERBOSE: Found 2 certificates in CurrentUser store
VERBOSE: Using certificate QlikClient and user <my account>
VERBOSE: Raw output: 
VERBOSE: Adding header x-Qlik-Xrfkey: dnshzmhgpratknjz
VERBOSE: Calling Get for https://DEVQLIK:4242/qrs/about?xrfkey=dnshzmhgpratknjz
VERBOSE: GET https://devqlik:4242/qrs/about?xrfkey=dnshzmhgpratknjz with 0-byte payload
Invoke-RestMethod : Unable to connect to the remote server
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:63 char:19
+         $result = Invoke-RestMethod @paramInvokeRestMethod @params
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by Sandheep33** [comment]
Hi Ahaydon, Thanks for your reply!!

I have already tried to connect the server using through certificates. Even though it was failing.  Please go through below cmds.  

//// fetching first server certificates. 

PS C:\Windows\system32> gci cert:\CurrentUser\My | where {$_.issuer -eq 'CN=Server1-CA'} | Connect-Qlik server1  


buildVersion      : 27.3.3.0
buildDate         : 3/11/2021 17:52:03 PM
databaseProvider  : Devart.Data.PostgreSql
nodeType          : 1
sharedPersistence : True
requiresBootstrap : False
singleNodeOnly    : False
schemaPath        : About



//// triggering the resp. tasks.  
PS C:\Windows\system32> Start-QlikTask "Reload task of Reloads Monitor1" 

/// fetching second server certificates. Got failed

PS C:\Windows\system32> gci cert:\CurrentUser\My | where {$_.issuer -eq 'CN=server2-CA'} | Connect-Qlik server2
gci : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ gci cert:\CurrentUser\My | where {$_.issuer -eq 'CN=DEV-QLIKSENSE....
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Get-ChildItem], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.GetChildItemCommand


/// Also tried with cmds which you provided.  

PS C:\Windows\system32> Get-ChildItem cert:\CurrentUser\My | Where-Object Issuer -eq 'CN=server2-CA' | Connect-Qlik server2
Where-Object : The 'Ieq' operator failed: The remote server returned an error: (403) Forbidden..
At line:1 char:38
+ ... ntUser\My | Where-Object Issuer -eq 'CN=DEV-QLIK-QLIKSENSE.....
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ([Subject]
  CN...517BDFE7000BF
:PSObject) [Where-Object], PSInvalidOperationException
    + FullyQualifiedErrorId : OperatorFailed,Microsoft.PowerShell.Commands.WhereObjectCommand
 
But still i can fetch server2 certificates : 
PS C:\Windows\system32> Get-ChildItem cert:\CurrentUser\My | Where-Object Issuer -eq 'CN=server2-CA'


    Directory: Microsoft.PowerShell.Security\Certificate::CurrentUser\My


Thumbprint                                Subject                                                                                                                        
----------                                -------                                                                                                                        
D**A*****************FE7000BF  CN=QlikClient

**Comment by Sandheep33** [comment]
Hi Ahaydon,

Any update on it?

**Comment by Sandheep33** [comment]
Getting really urgent to us, can you please suggest on it?

**Comment by Nillth** [comment]
You may have more than one certificate in the User Store, as such filtering on just the issuer will not guarantee only one certificate is being passed to the connect-qlik function

Also, you do not have to pipeline the certificate in, you can do something like this, where you get the certificate and hold it in a variable, then pass the variable to the connect-qlik function.
Note, I am looking at BOTH the Issuer & the Subject to make sure I am getting the QlikClient certificate (As that is the one you need to connect)

$Certificate = Get-ChildItem cert:\CurrentUser\My | Where-Object {$_.Issuer -eq 'CN=server2-CA' -and $_.Subject -eq "CN=QlikClient"} 
Connect-Qlik -Certificate $Certificate -Computername server2 -TrustAllCerts

**Comment by Sandheep33** [comment]
Yes, it works now. Thanks for the suggestion.
