### ISSUE TITLE
Add-QlikTrigger OnFail doesn't work

### ISSUE THREAD

**Issue by iamsalman20** [ahaydon/Qlik-Cli-Windows#156]
Hello,

I am using Qlik-CLI for adding triggers to my Reloadtask.
OnSuccess trigger is created successfully with command:
`Add-QlikTrigger -taskId $myTask.id -name "Task success" -OnSuccess $myTask.id`
But the following command gives error:
`Add-QlikTrigger -taskId $myTask.id -name "Task failed" -OnFail $myTask.id`
The error I get:
```
Add-QlikTrigger : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Add-QlikTrigger -taskId $myTask.id -name "Task failed ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidArgument: (:) [Add-QlikTrigger], ParameterBindingException
+ FullyQualifiedErrorId : AmbiguousParameterSet,Add-QlikTrigger
```

**Comment by Nillth** [comment]
Hell iamsalman20,

if you run the PowerShell command ```Get-Help Add-QlikTrigger``` you will get a list of available parameters on the function.

Digging around it looks like the -OnFail parameter was removed in commit  8aa4a09 however it appears that the documentation was not updated to reflect this. [Add-QlikTrigger](https://ahaydon.github.io/Qlik-Cli-Windows/Add-QlikTrigger.html)

The following can be used to create a OnFailure Task Trigger 

```PowerShell
$TaskID = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"

$TriggerName = "On Task Failure"
$OnFailure = $TaskID #,$TaskID

$update = @{
	compositeEvents = @(
		@{
			name = $TriggerName;
			enabled = $true;
			eventType = 1;
			reloadTask = @{
				id = $taskId
			}
			timeConstraint = @{
				seconds = 0;
				minutes = 360;
				hours = 0;
				days = 0;
			};
			compositeRules = @($OnFailure | ForEach-Object {
            #RuleState: 1=OnSuccess,2=OnFailure
					@{
						ruleState = 2;					
						reloadTask = @{
							id = $_
						}
					}
				});
			privileges = @("read", "update", "create", "delete")
		}
	)
}
$json = $update | ConvertTo-Json -Compress -Depth 10

return Invoke-QlikPost "/qrs/reloadtask/update" $json
```

**Comment by iamsalman20** [comment]
Hi @Nillth thanks for your response. I am aware of the API call that you mentioned but I wanted to do this using Qlik-CLI as everything else in my PS script is using CLI commands. Since you mentioned, -OnFail was removed in one of the commits, is there a specific reason? Are there plans to bring this functionality back in some other way or command? From a user's perspective it makes perfect sense to have -OnFail trigger if we have -OnSuccess trigger

**Comment by iamsalman20** [comment]
@Nillth Thanks for the response. That solves my problem!
