### ISSUE TITLE
Simple Request

### ISSUE THREAD

**Issue by dttspresident** [ahaydon/Qlik-Cli-Windows#157]
Hello all.  I am new to using Qlik CLI and unfamiliar with PowerShell. (setting the stage - Using Qlik Sense Enterprise February 2021).

I am hoping to pass in a date parameter to a subroutine on our Qlik server - similar to a batch process with command line.

Can someone give me a simple line of code to show how to do that?

I was thinking to use the QlikReloadTask option - but can use some help.

Thank you,

**Comment by levi-turner** [comment]
Can you elaborate a bit more what you hope to accomplish? Pass a date to a variable to be called in a Qlik load script?

**Comment by Nillth** [comment]
Stale, reopen if required with additional information requested.
