### ISSUE TITLE
Update-QlikDataConnection credentials causes domain to drop

### ISSUE THREAD

**Issue by aburnsy** [ahaydon/Qlik-Cli-Windows#159]
The Update-QlikDataConnection function utilises  .GetNetworkCredential().Username to fetch the user ID for the connection credentials. However, this does not include the domain, which would be under GetNetworkCredential().Domain

If the domain is required, a workaround is to pass an additional "\" at the beginning of the username. Thus GetNetworkCredential().Username would return the full domain and username.

**Comment by ahaydon** [comment]
Fixed in v1.21.1
