### ISSUE TITLE
Importing new Nodes and Virtual Proxy from Json with ERROR Invoke-RESTmethod

### ISSUE THREAD

**Issue by Kev-kutkin** [ahaydon/Qlik-Cli-Windows#161]
Hi, I am trying to migrate new nodes and virtual proxy from different server environments, server A to server B. I am using Qlik-Cli to automate it. I managed to export the content to a Json file from server A. However, I am facing the issue of importing new Nodes and also Virtual Proxy to server B from server A. The Json source's content is shown below. 

![virtualproxy_p1](https://user-images.githubusercontent.com/25189239/135786970-f3e66d01-8242-4cbb-9402-6f0fa1616545.jpg)

![virtualproxy_p2](https://user-images.githubusercontent.com/25189239/135786982-23a3c7e1-e1c8-4791-b490-fb392ef2e9e0.jpg)

The script and the ERROR that I have used and faced  are shown below.

![virtualproxy_script](https://user-images.githubusercontent.com/25189239/135787024-c98d5c7c-3c60-42e8-8824-8f3cf732d106.jpg)

Please advice me what is causing the error. 
Also, do share potential solution to allow me to import the Json content for the imports of new Node and Virtual Proxy . 

Thanks.

**Comment by ahaydon** [comment]
I suggest changing the `defaultVirtualProxy` to false as it is not possible to create a default virtual proxy, you may also need to remove the value for `loadBalancingServerNodes` as the node ID will be different for each site.

If you still have issues please run the `Import-QlikObject` with the `-verbose` switch and provide the output as this may provide useful information on the issue.
