### ISSUE TITLE
[Help Wanted] Is there a way to export the Qlik Load Script?

### ISSUE THREAD

**Issue by aburnsy** [ahaydon/Qlik-Cli-Windows#164]
We have roughly 300 apps in our cluster. We need to update some apps which are referencing older versions of scripts we use. 
I'm wondering is there a way to export all the load scripts to identify the apps we need to update.

**Comment by ahaydon** [comment]
The load script can only be accessed via the engine API using websocket, so this is not possible with Qlik-Cli for Windows, however you could use qlik-cli from qlik.dev. There is an example for how to set the script, and getting the script just requires replacing set with get in the command. https://qlik.dev/tutorials/get-started-with-qlik-cli/#add-a-load-script-to-the-app.

You will need to first get connected to the server:

```sh
qlik context create qse --server https://localhost --server-type windows
qlik context use qse
```

Then the command you would use would be as follows:

```sh
qlik app script get --app <appId>
```

**Comment by aburnsy** [comment]
Thanks Adam. I had thought that library worked with SaaS only - good to know
