### ISSUE TITLE
Search text within an app

### ISSUE THREAD

**Issue by itsik85** [ahaydon/Qlik-Cli-Windows#172]
Hi,
I would like to know if there is a possibility to present a QV/QS application in a textual way or alternatively to search for text in the entire application: in script, objects, variables, dimensions, expressions, etc.

I thought maybe using the Export-QlikMetadata function, or actually this function refers to a completely different operation?
Thank you very much for your help!

**Comment by ahaydon** [comment]
The Export-QlikMetadata command is for exporting SAML metadata from a virtual proxy.

Qlik-Cli for Windows works with the Qlik Sense Repository service APIs, it cannot connect to the engine as that would require use of websockets. To evaluate expressions on objects, variables, etc., would require use of the engine.

You can evaluate engine expressions using another tool, also called qlik-cli, have a look here https://qlik.dev/libraries-and-tools/qlik-cli. The relevant command is `qlik app eval`, more infor can be found at https://qlik.dev/libraries-and-tools/qlik-cli/app-eval.

**Comment by itsik85** [comment]
Sorry for my lack of knowledge, but is it possible to install this library and your library in PowerShell, together? Both modules have the same name ...
