### ISSUE TITLE
Multiple Certificates Issue : Node is disconnecting from QMC

### ISSUE THREAD

**Issue by Sandheep33** [ahaydon/Qlik-Cli-Windows#173]
Hi Ahaydon,

We are using Qlik-CLI for import&export qvf files from one environment to another (using external task from QMC). So, had to attach both Qliksense environment certificates on one of the scheduler node. As expected, the task is completed and we are able to do the job. But the issue is that often the scheduler node is disconnecting from QMC and its pointing to the another node certificate, not to the actual one when we checked the log. 

To solve this quickly, we always removing the other environment certificates and reimporting the certificates. Could you please suggest any solution for this? Hope the explanation is clear, let me know in case of any doubts.

**Comment by levi-turner** [comment]
You can use the `Get-PfxCertificate` command to read the certificate from disk (rather than from the certificate store on a Qlik Sense node). Example taken from [here](https://github.com/ahaydon/Qlik-Cli-Windows/wiki/Advanced-usage#multi-site-operations):

```powershell
PS C:\Temp>Get-PfxCertificate .\qlikserver01-client.pfx | `
Connect-Qlik -ComputerName qlikserver01.domain.ad -UserName INTERNAL\sa_api -TrustAllCerts
PS C:\Temp>Get-QlikApp -filter "customProperties.value eq 'Yes'" | `
foreach {Export-QlikApp -id $_.id -filename "$($_.name).qvf"}
PS C:\Temp>Get-PfxCertificate .\qlikserver02-client.pfx | `
Connect-Qlik -ComputerName qlikserver02.domain.ad -UserName INTERNAL\sa_api -TrustAllCerts
PS C:\Temp>Get-ChildItem -Recurse -Filter *.qvf | `
foreach {Import-QlikApp -file $_.Fullname-name $_.Basename -upload} | `
Publish-QlikApp -stream ExampleStream
```

**Comment by Sandheep33** [comment]
Hi Levi,

It worked. Thank you.
