### ISSUE TITLE
Copy bookmarks from one app to another

### ISSUE THREAD

**Issue by Sandheep33** [ahaydon/Qlik-Cli-Windows#174]
Hi Ahaydon,

Thank you for your support!!!. Can you please suggest a way to copy the bookmark as well from one qliksense app to another???

Situation : Right now, we are copying apps using qlik-cli to another environment, but Community bookmarks are not appearing.

Please let me know if you need additional information.

**Comment by ahaydon** [comment]
It is not possible to export community content with an app export, you would first need to promote it to base content and then it would be exported. The metadata such as the owner and published/approved status would need to be saved separately as it is not stored in QVF files. After importing you would then need to update the objects in the QRS with the correct owner and published/approved state.
