### ISSUE TITLE
qlik_sense_purge_unused_user_access_passes.ps1

### ISSUE THREAD

**Issue by LenHoover** [ahaydon/Qlik-Cli-Windows#175]
Hi,

I'm looking for this script qlik_sense_purge_unused_user_access_passes.ps1, please advise?

Thanks

**Comment by ahaydon** [comment]
It looks like the script was deleted from the repo, here is a link to the commit before the deletion. https://github.com/levi-turner/QlikSenseScripts/blob/c905cba45c99c920f04479166c6200760284a3fd/qlik_sense_purge_unused_user_access_passes.ps1

**Comment by levi-turner** [comment]
Thanks for deciphering my messy repo, @ahaydon.

@LenHoover : 

For the token model: https://github.com/levi-turner/QlikSenseScripts/blob/master/qs-cli/qs-cli-remove_tokens.ps1

For the professional / analyzer model: https://github.com/levi-turner/QlikSenseScripts/blob/master/qs-cli/qs-cli-remove_professional_analyzer_licenses.ps1
