### ISSUE TITLE
How to create a Qlik Sense Stream automatically using powershell

### ISSUE THREAD

**Issue by LenHoover** [ahaydon/Qlik-Cli-Windows#176]
Hi guy's,

I need some assistance please, how do i go about creating a new stream on Qlik Sense with a powershell script?
So, when i invoke the powershell script i want to pass in input parameters like Stream name, custom properties etc which will then
create the stream automatically.

Many thanks

Regards,
Lennon Hoover

**Comment by craigybrett** [comment]
I need to do the same but can't find any proper examples

**Comment by ahaydon** [comment]
Streams are created using the `New-QlikStream` command, e.g.
```powershell
New-QlikStream -name 'My Stream' -customProperties 'ReadAccess=Analyzer Users'
```
