### ISSUE TITLE
How to use New-QlikStream

### ISSUE THREAD

**Issue by LenHoover** [ahaydon/Qlik-Cli-Windows#177]
Hi,

I'm trying to use the New-QlikStream function to create a new stream on qlik sense. I can successfully create the stream using the function however i cant get it to assign a custom property :-(

Scenario : 
- The custom property is called StreamGrp (resource type - Streams) which has values ABC and DEF.
- I need to create a new stream called ABC and assign the custom property StreamGrp to ABC using the New-QlikStream function in powershell.

Can you please send me an example of how to do this then i can see where i am going wrong?

Thanks in advance

Regards,
Len

**Comment by levi-turner** [comment]
This is an approach: `New-QlikStream -Name ABC -customProperties StreamGrp=ABC`

**Comment by LenHoover** [comment]
Excellent! Thanks so much.....i tested it and its work
