### ISSUE TITLE
Support for Powershell Core

### ISSUE THREAD

**Issue by naavis** [ahaydon/Qlik-Cli-Windows#179]
The readme states Powershell 4.0 is required to use Qlik-Cli. I have been successfully using the module with Powershell 5.1 too, and I assume the readme means "Powershell 4.0 **or later**" in reality.

Does the module officially support Powershell Core too?

**Comment by ahaydon** [comment]
Hi @naavis, the statement that PowerShell 4.0 is required was intended to mean 4 or later as PS v5.1 has been supported from the start. I agree that this is not clear though so I will update it to say 4.0 or later. The module does also support PowerShell Core on all OS that PS Core runs on, and is tested on the latest version of Core with every new release.

Thanks for reporting this, I will get this information updated to be more clear.
