### ISSUE TITLE
Disabling service using QlikCli

### ISSUE THREAD

**Issue by abdulvajid4525** [ahaydon/Qlik-Cli-Windows#182]
I am able to enable  service by using
Update-QlikNode -id tqdwfuygfwyvdwhbvh -engineEnabled -name Rim1 -nodePurpose ProductionAndDevelopment -printingEnabled -proxyEnabled -schedulerEnabled

But I can't disable the scheduler service using
Update-QlikNode -id tqdwfuygfwyvdwhbvh -engineEnabled -name Rim1 -nodePurpose ProductionAndDevelopment -printingEnabled -proxyEnabled. Please let me know how a service in Nodes can be disabled using QlikCli

**Comment by ahaydon** [comment]
You can disable the scheduler using `Update-QlikNode -id tqdwfuygfwyvdwhbvh -engineEnabled -name Rim1 -nodePurpose ProductionAndDevelopment -printingEnabled -proxyEnabled -schedulerEnabled:$false`
