### ISSUE TITLE
Updating virtual proxy

### ISSUE THREAD

**Issue by abdulvajid4525** [ahaydon/Qlik-Cli-Windows#184]
Hi,
Q.No1)
I need to update **only** loadbalancingservernodes in virtual proxy. In the current scenario our system SAML sso authentication
Update-QlikVirtualProxy -id jgdfahbfbajkbfjabasbbfa -loadBalancingServerNodes Central
whether this step is correct?
Q.No2)
I need to add more nodes in loadBalancingServerNodes eg: Update-QlikVirtualProxy -id jgdfahbfbajkbfjabasbbfa -loadBalancingServerNodes Central,rim1
What is the correct syntax. Please help on both points

**Comment by countnazgul** [comment]
The `loadBalancingServerNodes` parameter should be array of either node `id` or node `host name`

![image](https://user-images.githubusercontent.com/22850/170188356-76c862a3-caf9-45b5-a532-98a68ed9a7f5.png)

**Comment by abdulvajid4525** [comment]
okay...the syntax will be Update-QlikVirtualProxy -id jgdfahbfbajkbfjabasbbfa -loadBalancingServerNodes id1, id2

can you please confirm on this

**Comment by countnazgul** [comment]
Yep. Combination is also possible

`Update-QlikVirtualProxy -id jgdfahbfbajkbfjabasbbfa -loadBalancingServerNodes id1,id2,HostName1`

**Comment by abdulvajid4525** [comment]
Can you please confirm that the above syntax will not update any other parameters except **loadBalancingServerNodes**  in the  respective virtual proxy.

**Comment by countnazgul** [comment]
Correct. Only the `loadBalancingServerNodes` will be updated. 
Qlik-cli will first get the full info about the object (in this case virtual proxy), update (locally) the required sections (based on the provided arguments) and will send the altered object back to Qlik
