### ISSUE TITLE
Remove customproperties from all QlikSense Users

### ISSUE THREAD

**Issue by izak004** [ahaydon/Qlik-Cli-Windows#192]
Hello Experts,

I am new to CLI in general, and would appreciate any help with this issue.
In QlikSense, I have a lot of users with custom properties assigned.

Is there a way though CLI to remove all of the custom properties from all the users?
Can someone please help with the code?

Thanks so much

**Comment by ahaydon** [comment]
If you delete the custom property or the value it will be removed from all the users.
