### ISSUE TITLE
Delete unpublished apps of inactive users using qlik-cli

### ISSUE THREAD

**Issue by ShalakaKshirsagar** [ahaydon/Qlik-Cli-Windows#194]
Request you to ping the code to Delete unpublished apps of inactive users.
I dont want to delete published apps of inactive users.

using qlik-cli scripting.

**Comment by ShalakaKshirsagar** [comment]
hello @ahaydon ,
Request you to respond.

**Comment by ahaydon** [comment]
Using the `Get-QlikApp` command you can filter the results by owner to check if the user is inactive and also check the published state of the app, the output can then be piped into the `Remove-QlikApp` command. The following example shows how to do this:
```powershell
Get-QlikApp -Filter "owner.inactive eq true and published eq false" | Remove-QlikApp
```
