### ISSUE TITLE
Internal Server error while exporting app.

### ISSUE THREAD

**Issue by SrinivasaMutha245** [ahaydon/Qlik-Cli-Windows#196]
Hi Team,

I am getting internal server error when i am trying to run export-qlikapp.
Below is the error information.

PS C:\Users> Get-QlikApp -id 'd4328854-cf7c-438f-adb2-3588181cb541' | Export-QlikApp
Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:66 char:23
+ ... $result = Invoke-RestMethod @paramInvokeRestMethod @params
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Thanks

**Comment by ahaydon** [comment]
Can the app be exported manually through the QMC?
How big is the app?
Are you using the latest version of Qlik-Cli?

Please try running the export with the `-Verbose` switch, this will provide more details about the API calls being made.

**Comment by SrinivasaMutha245** [comment]
Hi,

App size is 52 MB.
Version is 31.6

Below is the otuput after using -verbose.

PS C:\Users> Get-QlikApp -id 'd4328854-cf7c-438f-adb2-3588181cb541' | Export-QlikApp -Verbose
VERBOSE: filename=
VERBOSE: file=d4328854-cf7c-438f-adb2-3588181cb541.qvf
VERBOSE: Raw output:
VERBOSE: Adding header x-Qlik-Xrfkey: ckvuhurypxbsjosr
VERBOSE: Calling Post for https://INP44XPAPP4159:4242/qrs/app/d4328854-cf7c-438f-adb2-3588181cb541/export/08d2c7ac-7d19-4292-8a4f-904845584f4e?xrfkey=ckvuhurypxbsjosr
VERBOSE: POST https://inp44xpapp4159:4242/qrs/app/d4328854-cf7c-438f-adb2-3588181cb541/export/08d2c7ac-7d19-4292-8a4f-904845584f4e?xrfkey=ckvuhurypxbsjosr with -1-byte payload
Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:66 char:23
+ ...            $result = Invoke-RestMethod @paramInvokeRestMethod @params
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by SrinivasaMutha245** [comment]
I am able to export manually.

**Comment by ahaydon** [comment]
Please confirm the version of Qlik-Cli as 31.6 is not a valid version. Could you also confirm the version of Sense you are using.
