### ISSUE TITLE
Issue with adding a stream with new-qlikstream

### ISSUE THREAD

**Issue by Toteroni** [ahaydon/Qlik-Cli-Windows#201]
I'm trying to add a new stream with the New-QlikStream command but running into either (400) Bad Request or (409) Conflict errors.
I have "qlikview_supplychainusage" custom property value under "AppAnalysts" in the Custom Properties tab (qliksense.com/qmc/customproperties)

Stuck on these 2 things:
What is the correct way to add a Qlik Stream with custom properties?
New-QlikStream -name "TestStream" -customProperties "AppAnalysts", "qlikview_supplychainusage"
Can't figure out the correct order for the string and always get the 400 or 409 errors.
<img width="575" alt="customProperty" src="https://user-images.githubusercontent.com/13453157/221965029-b93a3af2-9984-416b-aed0-4cd6efd62f37.png">

And what is the correct way to add a Qlik Stream with an AD account as an owner?
New-QlikStream -name "TestStream2" -owner "domain\service_account" 
This command creates the stream but sets me (domain\toteroni, account running the script) as the owner.

Thank you very much!

**Comment by ahaydon** [comment]
There are a couple of different ways you can assign custom properties, here are some examples:
```powershell
#string
New-QlikStream -name "TestStream" -customProperties "AppAnalysts=qlikview_supplychainusage"

#hashtable
New-QlikStream -name "TestStream" -customProperties @{AppAnalysts="qlikview_supplychainusage"}
```

Your example for assigning an owner is correct, does the user exist in the repository?

**Comment by Toteroni** [comment]
Thank you for the examples! Closed.
The owner does exist in the repository..Not sure what could be going on.
I'll be running this script on the service account so it doesn't matter ultimately.

Thank you again.
