### ISSUE TITLE
Import QVF and set owner

### ISSUE THREAD

**Issue by mattiasthalen** [ahaydon/Qlik-Cli-Windows#203]
When importing an app, can I assign an owner, so that it ends up in that user’s work stream?

**Comment by Toteroni** [comment]
I don't think you can assign an owner with import-QlikApp...But you can get the App ID of the newly imported app and update the owner:

Update-QlikApp -id $AppID -owner "domain\username"

**Comment by mattiasthalen** [comment]
Ah ok, so a two step approach.That could work, thanks!On 9 Mar 2023, at 19:54, Toteroni ***@***.***> wrote:﻿
I don't think you can assign an owner with import-QlikApp...But you can get the App ID of the newly imported app and update the owner:
Update-QlikApp -id $AppID -owner "domain\username"

**Comment by ahaydon** [comment]
As the `Import-QlikApp` command outputs the details of the new app including the ID, you could pipe that into the `Update-QlikApp` command. E.g.

```powershell
Import-QlikApp -File MyApp.qvf -Upload | Update-QlikApp -Owner "domain\username"
```
