### ISSUE TITLE
Get qlik task trigger

### ISSUE THREAD

**Issue by itsik85** [ahaydon/Qlik-Cli-Windows#208]
Hi,

I have a task named Main Task that contains a "task event" type trigger.
This task is activated by the trigger, when a task named Slave Task ends successfully.
How can I access and receive all the "successfully completed tasks" type triggers for each task.

I have attached a picture with triggers that activate the task - how can I get the list of these triggers with their properties?

![image](https://github.com/ahaydon/Qlik-Cli-Windows/assets/13830285/69a9a2ff-75f4-4c41-93e3-8e67796c2ddb)

**Comment by itsik85** [comment]
any ideas?

**Comment by ahaydon** [comment]
The task events in the API are known as Composite Events, they are documented at https://help.qlik.com/en-US/sense-developer/May2023/APIs/RepositoryServiceAPI/index.html?page=53

You can get a list of composite events using `Invoke-QlikGet /qrs/compositeEvent`, to get the events for a particular task you can use a filter. E.g.

```powershell
Invoke-QlikGet /qrs/compositeEvent -filter "reloadTask.id eq 00202916-b776-410f-84f2-150482e2ff8f"
```

**Comment by itsik85** [comment]
Perfect! 
Thank you very much!
