### ISSUE TITLE
Reload Status of an app in Qlik Sense using Qlik CLI

### ISSUE THREAD

**Issue by SathvikBellala** [ahaydon/Qlik-Cli-Windows#210]
Hi Ahaydon,

I have been using the CLI commands for getting the reload status of an app from Qlik Saas but I am not able to get the data based on the Date & Time functions as there are in different formats  I believe this is due to the Qlik-Cli using only the "Task" API while the execution time is provided by the "Taskoperational" API. 
So please do provide a solution for this..!
<img width="687" alt="Date" src="https://github.com/ahaydon/Qlik-Cli-Windows/assets/100081278/5f685df0-610d-4cb1-a7bc-d524a5e15005">

Thanks & Regards,
Sathvik Bellala

**Comment by countnazgul** [comment]
This repo is for `Qlik CLI Windows`. It cant be used with SaaS and only with Qlik Sense Enterprise on Windows (QSEoW). 

From the screenshot i can see that you are using [Qlik CLI](https://github.com/qlik-oss/qlik-cli). So i could suggest to you to open an issue there or ask on the Slack channel or ask the [Community](https://community.qlik.com/).
