### ISSUE TITLE
Unable to Create Active Directory User Directory Connector with Qlik-Cli PowerShell Module

### ISSUE THREAD

**Issue by RaresAgachiRelevance** [ahaydon/Qlik-Cli-Windows#214]
I'm encountering a problem while attempting to create an Active Directory user directory connector in QMC using the Qlik-Cli PowerShell module. The issue I'm facing relates to the -type parameter, as it doesn't accept the expected values, and I'm unsure about how to use the -settings parameter correctly.

Reproduction Steps:

Use the Qlik-Cli PowerShell module.
Try to create a user directory connector with the type "Active Directory" or "Microsoft Active Directory" using the -type parameter.
Observe the error or issue encountered.

Expected Behavior:
The -type parameter should accept "Active Directory" or "Microsoft Active Directory" as values when creating a user directory connector.

Actual Behavior:
The -type parameter does not accept "Active Directory" or "Microsoft Active Directory" as values and results in an error.

Example Code Snippet:

function Create-AD {
    # Define the parameters for the User Directory Connector
    $udcName = "Active Directory HRO-L"
    $udcType = 'Active Directory'
    $udcSettings = @{
        "Path" = "LDAP://example.com:3268"
        "User name" = "example\qlikuser"
        "Additional Ldap Filter" = "(|(memberof=CN=Group1,OU=Groups,DC=example,DC=com)(memberof=CN=Group2,OU=Groups,DC=example,DC=com))"
    }
    New-QlikUserDirectory -name $udcName -type $udcType -customproperties $udcSettings -Verbose -syncOnlyLoggedInUsers "False"
}

Additional Information:

I have referred to the [New-QlikUserDirectory documentation](https://github.com/ahaydon/Qlik-Cli-Windows/blob/master/docs/New-QlikUserDirectory.md) for guidance, but it lacks specific instructions on setting the -type and -settings parameters correctly.
   
Please feel free to share your insights, suggestions, or solutions to help resolve this issue. Thank you for your support!

**Comment by ahaydon** [comment]
I suggest creating the connection in the QMC and then using `Get-QlikUserDirectory` to view the settings that get created, when doing this you can see that the type should be `Repository.UserDirectoryConnectors.LDAP.ActiveDirectory`.

**Comment by RaresAgachiRelevance** [comment]
> I suggest creating the connection in the QMC and then using `Get-QlikUserDirectory` to view the settings that get created, when doing this you can see that the type should be `Repository.UserDirectoryConnectors.LDAP.ActiveDirectory`.

You're absolutely right, it seems straightforward now that you put it like that, but it didn't cross my mind at first. This principle can be applied to any change that can be made manually in the QMC. This solved the issue, thanks!
